### ISSUE TITLE
Include auth token header only for API requests

### ISSUE THREAD

**Issue by kvikshaug** [DD-DeCaF/metabolica-ui-login#8]
Right now, the Authorization header is sent for all URLs in the `isTrustedURL` method, which also includes static resources and more. It should be further limited to API services.

**Comment by matyasfodor** [comment]
What's the best way to deal with this? I'd consider using a different domain / CDN for static content.

**Comment by kvikshaug** [comment]
I think the best and most direct way is to just add an explicit list of API endpoints to match against, like trusted urls.

We should consider a CDN for statics regardless though. My first concern there is how would we want to solve that for on-premise installations.

**Comment by matyasfodor** [comment]
I think they should do it on their own for on-premise installations. I'm not a big fan of the explicit list of API endpoints. I'd rather define an api root url (like `/api` or `/api/v1`). Just to make it easier to add new endpoints.

**Comment by kvikshaug** [comment]
Wontfix; replaced by new frontend.
